// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsnP3H9iIvNar40zDJ5fWl1TwLIPrgxLU',
    appId: '1:867687215377:web:70719860ad3a863fd69cb0',
    messagingSenderId: '867687215377',
    projectId: 'inheritance-f2871',
    authDomain: 'inheritance-f2871.firebaseapp.com',
    storageBucket: 'inheritance-f2871.firebasestorage.app',
    measurementId: 'G-4NCND52FHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqzbvP5fM4rbbD1JYOhjkKUhKXfubH7Jk',
    appId: '1:867687215377:android:0a031a46898e7932d69cb0',
    messagingSenderId: '867687215377',
    projectId: 'inheritance-f2871',
    storageBucket: 'inheritance-f2871.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAISgYzaaVO1Ygd8BtZJ7Qppc2xTS18FzU',
    appId: '1:867687215377:ios:e5123d689b81ba2dd69cb0',
    messagingSenderId: '867687215377',
    projectId: 'inheritance-f2871',
    storageBucket: 'inheritance-f2871.firebasestorage.app',
    iosBundleId: 'com.example.mySoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAISgYzaaVO1Ygd8BtZJ7Qppc2xTS18FzU',
    appId: '1:867687215377:ios:e5123d689b81ba2dd69cb0',
    messagingSenderId: '867687215377',
    projectId: 'inheritance-f2871',
    storageBucket: 'inheritance-f2871.firebasestorage.app',
    iosBundleId: 'com.example.mySoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsnP3H9iIvNar40zDJ5fWl1TwLIPrgxLU',
    appId: '1:867687215377:web:a5c2f79dadbe7b6ed69cb0',
    messagingSenderId: '867687215377',
    projectId: 'inheritance-f2871',
    authDomain: 'inheritance-f2871.firebaseapp.com',
    storageBucket: 'inheritance-f2871.firebasestorage.app',
    measurementId: 'G-T7N53HEZ4Y',
  );
}
